//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemacompra.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public Buy()
        {
            this.Buy_Detail = new HashSet<Buy_Detail>();
            this.PayDetail = new HashSet<PayDetail>();
        }
    
        public int id_buy { get; set; }
        public Nullable<System.DateTime> date_buy { get; set; }
        public string total_buy { get; set; }
        public string observation_buy { get; set; }
        public string state_buy { get; set; }
    
        public virtual ICollection<Buy_Detail> Buy_Detail { get; set; }
        public virtual ICollection<PayDetail> PayDetail { get; set; }
    }
}
