//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemacompra.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDetail
    {
        public int id_pd { get; set; }
        public Nullable<System.DateTime> date_pd { get; set; }
        public string pay_pd { get; set; }
        public string bank_pd { get; set; }
        public int Buy_id_buy { get; set; }
    
        public virtual Buy Buy { get; set; }
    }
}
